version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto8
  build:
    commands:
      - echo Entered the build phase
      - echo Build started on `date`
      - mvn install
    post_build:
      commands:
        - zip -r maadcars.zip target/maadcars-0.1.war
        - aws s3 cp maadcars.zip s3://codepipeline-us-east-1-485792357857/maad2/
        - echo Build completed successfully
    artifacts:
      files:
        - maadcars.zip
