version: 0.1
phases:
  build:
    commands:
      - echo Entered the build phase
      - echo Build started on `date`
      - mvn clean package
    post_build:
      commands:
        - echo Build completed successfully
        - mvn package
        - mv target/maadcars* ./
    artifacts:
        files:
          target/maadcars*/*
      discard-paths: yes
