version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto8
  build:
    commands:
      - echo Entered the build phase
      - echo Build started on `date`
      - mvn clean
    post_build:
      commands:
        - mvn install
        - echo Build completed successfully
        - Compress-Archive target/maadcars-0.1.war target/maadcars.zip
    artifacts:
      files:
        - target/maadcars.zip

