phases:
  install:
    runtime-versions:
      java: corretto8
  post_build:
    commands:
      - mvn package
      - mv target/maadcars-0.1.war ROOT.war
  artifacts:
    files:    
      - ROOT.war
